name: demo-app

app_namespace: default
address: https://kubernetes.default.svc

repository:
  url: git@github.com:vnhirenko/demo-app.git
  path: helm/demo-app

app_values: |
  replicaCount: 2

  serviceAccount:
    create: false

  service:
    type: ClusterIP
    port: 8080
  deployment:
    port: 8080

  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: "llab.com"
        paths:
          - path: /
            pathType: ImplementationSpecific
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
